spring.application.name=springBootDemo

spring.datasource.url= jdbc:postgresql://localhost:5432/springdata?currentSchema=typside_com_posts
spring.datasource.username= postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


